### PR TITLE
hello

### PR DESCRIPTION
**Pull request by jobscale**
i am japanese

### CODE REVIEW

**Comment by bestmomo** [comment]
Hello,

I dont understand why you make a method spoofing on Ajax PUT request.

**Comment by jobscale** [comment]
hello.

"FireFox, Chrome" is not support HTML request with "PUT, DELETE" browser. but have support add-on.
https://laravel.com/docs/5.2/routing#form-method-spoofing

**Comment by bestmomo** [comment]
Html forms doesn't support these verbs but not Ajax requests.

**Comment by jobscale** [comment]
browser is processing the javascript.

**Comment by bestmomo** [comment]
Yes but Ajax requests work with any verb, try it ;)

**Comment by jobscale** [comment]
No

**Comment by jobscale** [comment]
hello. thank you.
result do not support webdav. nginx of linux distribution package. (CentOS and Ubuntu)
but build by source is webdav enable.

**Comment by bestmomo** [comment]
Hello
So it's a local issue, just disable webdav or use another local server.

**Pull request closed without merging**
