### PR TITLE
async and newer dnsjs source of the  jquery file

### PR DESCRIPTION
**Pull request by UnrulyNatives**

### CODE REVIEW

**Comment by bestmomo** [comment]
Hello,
I wonder about the sync attribute. As there is a related library after jQuery load, mustn't keep the load order ?

**Comment by UnrulyNatives** [comment]
I don't know how to figure this out in case of jquery. I was just pointing out a place for improvement. 
My test site worked well with the change. 

I am sure that the main.js and plugins.js can be loaded with with the async though.

**Comment by bestmomo** [comment]
I read an article with load tests and with async on many scripts the order seems to be unpredictable.

**Comment by UnrulyNatives** [comment]
I started to use async after I saw here
https://developers.google.com/speed/pagespeed/insights/
that my site is too slow and the async was suggested.

On the other hand, in Laravel 5 I use now the asset pipeline is not working - as far as I can figure out the conclusion from the Google Insights.

Is there any way to increase speed of loading for L5 site?

**Comment by bestmomo** [comment]
Pages loading does not really depends on Laravel but casual HTTP. I trust [boilerplate](https://html5boilerplate.com) for this and I followed it for templates.

On framework side there was on Laracasts [an interesting discussion](https://laracasts.com/discuss/channels/general-discussion/why-laravel-is-sooo-slow) about Laravel speed.

**Pull request closed without merging**
