### PR TITLE
Update 2014_10_26_172107_create_posts_table.php

### PR DESCRIPTION
**Pull request by UnrulyNatives**

### CODE REVIEW

**Comment by bestmomo** [comment]
I began with French language for this example. If we want to change for English one, that would be a good thing, we need to change also all code in repositories and views !

**Comment by UnrulyNatives** [comment]
I can do it tomorrow

**Comment by bestmomo** [comment]
There is also "vu" that must be called "seen"

**Comment by bestmomo** [comment]
Done with [this commit](https://github.com/bestmomo/laravel5-example/commit/5d40d7f580bed31c03ab61a799d197ecd34509d3).

**Pull request closed without merging**
